version: '3.9'

#
# Have a look at the .env file -> used for configuration
#

services:
  yamp:
    build: ./
    networks:
      - yamp
    env_file:
      - .env
    ports:
      - "51820:51820/udp"
    volumes:
      - ./plugins:/plugins:ro

#  test_server:
#    build: test/server
#    profiles:
#      - testing
#    depends_on:
#      - yamp
#    networks:
#      - yamp
#    env_file:
#      - .env
#    cap_add:
#      - NET_ADMIN
#
#  test_client_inside:
#    build: test/client
#    profiles:
#      - testing
#    depends_on:
#      - yamp
#      - test_server
#    networks:
#      - yamp
#    env_file:
#      - .env
#    cap_add:
#      - NET_ADMIN
#    environment:
#      YAMP_TEST_CLIENT: inside
#
#  test_client_outside:
#    build: test/client
#    profiles:
#      - testing
#    depends_on:
#      - yamp
#      - test_server
#    networks:
#      - yamp
#    env_file:
#      - .env
#    environment:
#      YAMP_TEST_CLIENT: outside

networks:
  yamp:
