version: '3.9'

#
# Have a look at the .env file -> used for configuration
#

services:
  yamp:
    build: ./
    networks:
      - yamp
    hostname: yamp
    env_file:
      - ${ENV_FILE-.env}
    ports:
      - "51820:51820/udp"
      - "51821:51821/udp"
      - "51822:51822/udp"
    volumes:
      - ${PLUGIN_DIR-./plugins}:/plugins:ro
      - ${RULES_DIR-./rules}:/rules:ro
      - ./dependencies:/dependencies:ro

  test_server:
    build: test/server
    profiles:
      - testing
    depends_on:
      - yamp
    networks:
      - yamp
    hostname: testserver
    env_file:
      - .env-test
    cap_add:
      - NET_ADMIN

  test_client:
    build: test/client
    profiles:
      - testing
    depends_on:
      - yamp
      - test_server
    networks:
      - yamp
    hostname: testclient
    env_file:
      - .env-test
    cap_add:
      - NET_ADMIN

networks:
  yamp:
